//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""HackGrid"",
            ""id"": ""40569d78-f7a5-4e7e-8366-82946e70ac0c"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""5e38e74c-ea06-4ce5-af6b-c669b959b170"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""712d742d-961d-4810-b926-6cb73b629206"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""6a74ccc1-2e97-4fad-8b98-20e8f317ed32"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""7bcff23b-aba8-4720-bdf8-5f02bf3225cb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""36469e03-53a2-4196-9329-84a648762a0f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""96bf09b0-bb37-43de-bccd-13a9153e0ca2"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f3179c29-3cc7-4d5b-93b1-6a069ca614ba"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c2c9a652-58ab-4a1e-b9d4-eafbc1a82195"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""0db470d2-6903-4e18-ac14-73cbb91bfd8e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""eb80b168-d359-4de2-a352-ebc6a293ceb3"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1c1b8b88-5fe8-4a19-96ab-8173e0be1123"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""200ac5a0-467d-4932-b2b2-542a904698d9"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""00bf028d-e91c-4bcb-8ccf-3162a19e2a2a"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""93df7e22-8cb2-419d-bfb8-6d4a8b089e2c"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""778a5310-7f59-402e-8d15-84e20a623236"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""faaf2338-40ae-43bd-b5cc-e800d1a0e1bf"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d50a7eb3-3b8e-4d78-91d0-39a920006281"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01a829e1-fa90-4005-82a2-47da7e2e42ef"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Messager"",
            ""id"": ""8a07f226-ecfd-45c0-80f0-10ae2e70f9df"",
            ""actions"": [
                {
                    ""name"": ""NextMessage"",
                    ""type"": ""Button"",
                    ""id"": ""fdb9341c-ffb5-4f47-98c2-d2c87df3d51f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""eba6fe2e-81e9-41c5-ab9f-32115834e940"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""NextMessage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Main"",
            ""bindingGroup"": ""Main"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // HackGrid
        m_HackGrid = asset.FindActionMap("HackGrid", throwIfNotFound: true);
        m_HackGrid_Movement = m_HackGrid.FindAction("Movement", throwIfNotFound: true);
        m_HackGrid_Select = m_HackGrid.FindAction("Select", throwIfNotFound: true);
        m_HackGrid_Cancel = m_HackGrid.FindAction("Cancel", throwIfNotFound: true);
        // Messager
        m_Messager = asset.FindActionMap("Messager", throwIfNotFound: true);
        m_Messager_NextMessage = m_Messager.FindAction("NextMessage", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // HackGrid
    private readonly InputActionMap m_HackGrid;
    private IHackGridActions m_HackGridActionsCallbackInterface;
    private readonly InputAction m_HackGrid_Movement;
    private readonly InputAction m_HackGrid_Select;
    private readonly InputAction m_HackGrid_Cancel;
    public struct HackGridActions
    {
        private @InputActions m_Wrapper;
        public HackGridActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_HackGrid_Movement;
        public InputAction @Select => m_Wrapper.m_HackGrid_Select;
        public InputAction @Cancel => m_Wrapper.m_HackGrid_Cancel;
        public InputActionMap Get() { return m_Wrapper.m_HackGrid; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HackGridActions set) { return set.Get(); }
        public void SetCallbacks(IHackGridActions instance)
        {
            if (m_Wrapper.m_HackGridActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_HackGridActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_HackGridActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_HackGridActionsCallbackInterface.OnMovement;
                @Select.started -= m_Wrapper.m_HackGridActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_HackGridActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_HackGridActionsCallbackInterface.OnSelect;
                @Cancel.started -= m_Wrapper.m_HackGridActionsCallbackInterface.OnCancel;
                @Cancel.performed -= m_Wrapper.m_HackGridActionsCallbackInterface.OnCancel;
                @Cancel.canceled -= m_Wrapper.m_HackGridActionsCallbackInterface.OnCancel;
            }
            m_Wrapper.m_HackGridActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @Cancel.started += instance.OnCancel;
                @Cancel.performed += instance.OnCancel;
                @Cancel.canceled += instance.OnCancel;
            }
        }
    }
    public HackGridActions @HackGrid => new HackGridActions(this);

    // Messager
    private readonly InputActionMap m_Messager;
    private IMessagerActions m_MessagerActionsCallbackInterface;
    private readonly InputAction m_Messager_NextMessage;
    public struct MessagerActions
    {
        private @InputActions m_Wrapper;
        public MessagerActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @NextMessage => m_Wrapper.m_Messager_NextMessage;
        public InputActionMap Get() { return m_Wrapper.m_Messager; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MessagerActions set) { return set.Get(); }
        public void SetCallbacks(IMessagerActions instance)
        {
            if (m_Wrapper.m_MessagerActionsCallbackInterface != null)
            {
                @NextMessage.started -= m_Wrapper.m_MessagerActionsCallbackInterface.OnNextMessage;
                @NextMessage.performed -= m_Wrapper.m_MessagerActionsCallbackInterface.OnNextMessage;
                @NextMessage.canceled -= m_Wrapper.m_MessagerActionsCallbackInterface.OnNextMessage;
            }
            m_Wrapper.m_MessagerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @NextMessage.started += instance.OnNextMessage;
                @NextMessage.performed += instance.OnNextMessage;
                @NextMessage.canceled += instance.OnNextMessage;
            }
        }
    }
    public MessagerActions @Messager => new MessagerActions(this);
    private int m_MainSchemeIndex = -1;
    public InputControlScheme MainScheme
    {
        get
        {
            if (m_MainSchemeIndex == -1) m_MainSchemeIndex = asset.FindControlSchemeIndex("Main");
            return asset.controlSchemes[m_MainSchemeIndex];
        }
    }
    public interface IHackGridActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
    }
    public interface IMessagerActions
    {
        void OnNextMessage(InputAction.CallbackContext context);
    }
}
